sonar.projectKey=portfolio-e2e-workflow
sonar.organization=karthi231997
sonar.projectName=portfolio-fullstack-devops
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=app
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/.next/**
